version: "3.7"
services:

  # api:
  #   build: ./api
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     - mongo

  # ml:
  #   build: ./ml
  #   ports:
  #     - 5000:5000
    
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /Users/johnpaulada/mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root